package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/wailsapp/go-webview2/pkg/edge"
)

// exportYoutubeCookies reads cookies from the login WebView2 profile and writes
// them in Netscape format for yt-dlp --cookies. Faithful port of
// desktop/youtube-auth.cjs (isRelevantCookie / formatDomain / toNetscape...).
func exportYoutubeCookies(chromium *edge.Chromium, destPath string) (int, error) {
	cm, err := chromium.GetCookieManager()
	if err != nil {
		return 0, fmt.Errorf("cookie manager unavailable: %w", err)
	}
	defer cm.Release()

	list, err := cm.GetCookies("")
	if err != nil {
		return 0, fmt.Errorf("failed to read cookies: %w", err)
	}
	defer list.Release()

	count, err := list.GetCount()
	if err != nil {
		return 0, err
	}

	var lines []string
	lines = append(lines,
		"# Netscape HTTP Cookie File",
		"# Generated by Stream Media Board",
		"",
	)

	written := 0
	for i := uint32(0); i < count; i++ {
		cookie, err := list.GetItem(i)
		if err != nil {
			continue
		}
		domainRaw, _ := cookie.GetDomain()
		if !isRelevantCookie(domainRaw) {
			continue
		}
		name := sanitizeCookieValue(mustStr(cookie.GetName()))
		value := sanitizeCookieValue(mustStr(cookie.GetValue()))
		domain := formatDomain(domainRaw)
		if domain == "" || name == "" || value == "" {
			continue
		}
		cookiePath := mustStr(cookie.GetPath())
		if cookiePath == "" {
			cookiePath = "/"
		}
		secure := "FALSE"
		if ok, _ := cookie.GetIsSecure(); ok {
			secure = "TRUE"
		}
		includeSub := "FALSE"
		if strings.HasPrefix(domain, ".") {
			includeSub = "TRUE"
		}
		expires := toNetscapeExpiration(cookie)
		lines = append(lines, strings.Join([]string{
			domain, includeSub, cookiePath, secure,
			fmt.Sprintf("%d", expires), name, value,
		}, "\t"))
		written++
	}

	if written == 0 {
		return 0, fmt.Errorf("no usable YouTube/Google cookies were found - finish signing in and try again")
	}

	if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(destPath, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		return 0, err
	}
	return written, nil
}

func isRelevantCookie(domain string) bool {
	d := strings.ToLower(domain)
	return strings.Contains(d, "youtube.com") ||
		strings.Contains(d, "youtu.be") ||
		strings.Contains(d, "google.com")
}

func formatDomain(domain string) string {
	trimmed := strings.TrimSpace(domain)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, ".") {
		return trimmed
	}
	return "." + trimmed
}

func sanitizeCookieValue(value string) string {
	r := strings.NewReplacer("\t", "", "\r", "", "\n", "")
	return strings.TrimSpace(r.Replace(value))
}

func toNetscapeExpiration(cookie *edge.ICoreWebView2Cookie) int64 {
	exp, err := cookie.GetExpires()
	if err == nil && exp > 0 {
		return int64(exp)
	}
	return time.Now().Unix() + 60*60*24*365
}

func mustStr(s string, _ error) string {
	return s
}
